# https://docs.docker.com/compose/
services:
  web:
    build: ./web
    ports:
      - "80:8080"
    image: "web"
    # volumes:
    #   - /shared:/shared

  spaced-repitition:
    build: ./services/spaced_repitition
    image: "spaced-repitition"
    ports:
      - "1000:1000"

  # redis:
  #   build: ./services/redis
  #   ports:
  #     - "1200:1200"
  #   image: "lms-redis"
