# https://docs.docker.com/compose/
services:
  web:
    build: ./web
    ports:
      - "80:8080"
    image: "lms-web"
    # volumes:
    #   - /shared:/shared

  spaced-repitition:
    build: ./services/spaced_repitition
    image: "lms-spaced-repitition"
    ports:
      - "1000:1000"
    # volumes:
    #   - /shared:/shared
